"""creating tables

Revision ID: 223f35f7391f
Revises: 
Create Date: 2020-09-02 22:22:26.295671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223f35f7391f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confused_words',
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('word')
    )
    op.create_table('sentence_structure',
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('structure', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('word')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sentence_structure')
    op.drop_table('confused_words')
    # ### end Alembic commands ###
